/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: '#faf8ff',
        'surface-dim': '#d2d9f4',
        'surface-bright': '#faf8ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f2f3ff',
        'surface-container': '#eaedff',
        'surface-container-high': '#e2e7ff',
        'surface-container-highest': '#dae2fd',
        'on-surface': '#131b2e',
        'on-surface-variant': '#594046',
        'inverse-surface': '#283044',
        'inverse-on-surface': '#eef0ff',
        outline: '#8d7075',
        'outline-variant': '#e0bec4',
        'surface-tint': '#b81059',
        primary: '#970046',
        'on-primary': '#ffffff',
        'primary-container': '#be185d',
        'on-primary-container': '#ffd5dd',
        'inverse-primary': '#ffb1c3',
        secondary: '#575f69',
        'on-secondary': '#ffffff',
        'secondary-container': '#dbe3ef',
        'on-secondary-container': '#5d656f',
        tertiary: '#00554e',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#006f67',
        'on-tertiary-container': '#99efe4',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#ffd9e0',
        'primary-fixed-dim': '#ffb1c3',
        'on-primary-fixed': '#3f0019',
        'on-primary-fixed-variant': '#8f0042',
        'secondary-fixed': '#dbe3ef',
        'secondary-fixed-dim': '#bfc7d2',
        'on-secondary-fixed': '#141c24',
        'on-secondary-fixed-variant': '#3f4851',
        'tertiary-fixed': '#9cf2e8',
        'tertiary-fixed-dim': '#80d5cb',
        'on-tertiary-fixed': '#00201d',
        'on-tertiary-fixed-variant': '#00504a',
        background: '#faf8ff',
        'on-background': '#131b2e',
        'surface-variant': '#dae2fd',
        'rose-dark': '#9D174D',
        'navy-soft': '#1A2834',
        olive: '#64704D',
        'muted-slate': '#64748B',
        'line-rose': '#F7E3EB',
        'soft-blush': '#FBF1F5',
        'paper-canvas': '#FDF2F8',
        success: '#0F766E',
        warning: '#D97706',
        danger: '#DC2626',
        info: '#0369A1',
        'success-surface': '#ECFDF5',
        'warning-surface': '#FFF7ED',
        'danger-surface': '#FEF2F2',
        'info-surface': '#E0F2FE',
        'neutral-surface': '#F8FAFC',
      },
      fontFamily: {
        sans: ['Manrope', 'system-ui', '-apple-system', 'sans-serif'],
        manrope: ['Manrope', 'system-ui', '-apple-system', 'sans-serif'],
        syne: ['Syne', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'ui-monospace', 'monospace'],
      },
      fontSize: {
        'display-2xl': ['4.5rem', { lineHeight: '1.05', letterSpacing: '-0.03em', fontWeight: '800' }],
        'display-xl': ['3.75rem', { lineHeight: '1.1', letterSpacing: '-0.025em', fontWeight: '800' }],
        'display-lg': ['3rem', { lineHeight: '1.15', letterSpacing: '-0.02em', fontWeight: '800' }],
        'display-md': ['2.25rem', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '800' }],
        'display-sm': ['1.875rem', { lineHeight: '1.25', letterSpacing: '-0.015em', fontWeight: '700' }],
        'headline-lg': ['1.5rem', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-md': ['1.25rem', { lineHeight: '1.35', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-sm': ['1.125rem', { lineHeight: '1.4', letterSpacing: '-0.005em', fontWeight: '600' }],
      },
      letterSpacing: {
        tightest: '-0.04em',
        tighter: '-0.02em',
        tight: '-0.01em',
        normal: '0em',
        wide: '0.02em',
        wider: '0.05em',
        widest: '0.1em',
        atelier: '0.16em',
      },
      spacing: {
        'base': '4px',
        'space-1': '4px',
        'space-2': '8px',
        'space-3': '12px',
        'space-4': '16px',
        'space-5': '24px',
        'space-6': '32px',
        'gutter': '16px',
        'sidebar-expanded': '248px',
        'sidebar-collapsed': '80px',
      }
    },
  },
  plugins: [],
}
