name: Generate Supabase Types

on:
  push:
    branches:
      - fix/supabase-types

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          ref: fix/supabase-types

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Generate Types
        run: supabase gen types typescript --project-id ${{ vars.SUPABASE_PROJECT_REF }} > src/database.types.ts
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add src/database.types.ts
          git commit -m "chore: auto-generate Supabase types" || exit 0
          git push origin fix/supabase-types
